#!/usr/bin/env python3
"""Generate hps/hps_min.v - an Agilex 5 HPS + HPS-EMIF wrapper with the
internal HPS<->EMIF NoC bus wired up, from the *_inst.v of the two IPs.

Run after (re)generating the IP:
    qsys-generate hps/ip/hps_subsys/agilex_hps.ip     --synthesis=VHDL --part=A5ED013BB32AE4SCS
    qsys-generate hps/ip/qsys_top/emif_io96b_hps.ip   --synthesis=VHDL --part=A5ED013BB32AE4SCS
    python3 hps/gen_hps_min.py

agilex_hps.ip must have every FPGA<->HPS bridge disabled first
(H2F_Width / LWH2F_Width / f2s_data_width / f2sdram_data_width = 0,
 F2H_IRQ_Enable = false).
"""
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A_INST = os.path.join(ROOT, "hps/ip/hps_subsys/agilex_hps/agilex_hps_inst.v")
E_INST = os.path.join(ROOT, "hps/ip/qsys_top/emif_io96b_hps/emif_io96b_hps_inst.v")
OUT = os.path.join(ROOT, "hps/hps_min.v")


def parse(path):
    ports = []
    for line in open(path):
        m = re.match(
            r"\s*\.(\w+)\s*\(_connected_to_\w+_\),?\s*//\s*"
            r"(input|output|inout),\s*width = (\d+),\s*(\S+)",
            line,
        )
        if m:
            ports.append([m.group(1), m.group(2), int(m.group(3)), m.group(4).split(".")[-1]])
    return ports


def rng(w):
    return "" if w == 1 else "[%d:0] " % (w - 1)


def main():
    A = parse(A_INST)
    E = parse(E_INST)

    a_io = {p[0][len("io96b0_to_hps_"):]: p for p in A if p[0].startswith("io96b0_to_hps_")}
    e_io = {p[3]: p for p in E if p[3].startswith(("axi4_ch0", "ch0_axil"))}
    assert set(a_io) == set(e_io), set(a_io) ^ set(e_io)

    a_ext = [p for p in A if not p[0].startswith("io96b0_to_hps_")]
    e_ext = [p for p in E if not p[3].startswith(("axi4_ch0", "ch0_axil"))]

    L = []
    L.append("// ----------------------------------------------------------------------")
    L.append("// hps_min - Agilex 5 HPS + HPS-EMIF (DDR4); FPGA<->HPS bridges disabled.")
    L.append("//")
    L.append("// GENERATED by hps/gen_hps_min.py - do not edit by hand.")
    L.append("//")
    L.append("// The HPS clocks itself from hps_io_hps_osc_clk (HPS_CLK_25) and the")
    L.append("// EMIF from ref_clk (DDR4_REFCLK_p); the EMIF supplies the NoC")
    L.append("// clock/reset for the internal HPS<->EMIF path, so this block needs")
    L.append("// no fabric clock or reset.")
    L.append("// ----------------------------------------------------------------------")
    L.append("module hps_min (")
    decls = ["    %-6s %s%s" % (d, rng(w), nm) for nm, d, w, _ in (a_ext + e_ext)]
    L.append(" ,\n".join(decls))
    L.append(");")
    L.append("")
    L.append("    // ---- internal HPS <-> EMIF NoC bus (io96b0_to_hps) ----")
    for role, (nm, d, w, _) in sorted(a_io.items()):
        L.append("    wire %s io96b_%s;" % (rng(w).strip(), role))
    L.append("")
    L.append("    agilex_hps u_hps (")
    conn = []
    for nm, d, w, role in A:
        w_ = "io96b_" + nm[len("io96b0_to_hps_"):] if nm.startswith("io96b0_to_hps_") else nm
        conn.append("        .%s (%s)" % (nm, w_))
    L.append(" ,\n".join(conn))
    L.append("    );")
    L.append("")
    L.append("    emif_io96b_hps u_emif (")
    conn = []
    for nm, d, w, role in E:
        w_ = "io96b_" + role if role.startswith(("axi4_ch0", "ch0_axil")) else nm
        conn.append("        .%s (%s)" % (nm, w_))
    L.append(" ,\n".join(conn))
    L.append("    );")
    L.append("")
    L.append("endmodule")
    open(OUT, "w").write("\n".join(L) + "\n")
    print("wrote", OUT, "(%d external ports, %d internal bus wires)" % (len(a_ext) + len(e_ext), len(a_io)))


if __name__ == "__main__":
    main()
