// ----------------------------------------------------------------------
// hps_min - Agilex 5 HPS + HPS-EMIF (DDR4); FPGA<->HPS bridges disabled.
//
// GENERATED by hps/gen_hps_min.py - do not edit by hand.
//
// The HPS clocks itself from hps_io_hps_osc_clk (HPS_CLK_25) and the
// EMIF from ref_clk (DDR4_REFCLK_p); the EMIF supplies the NoC
// clock/reset for the internal HPS<->EMIF path, so this block needs
// no fabric clock or reset.
// ----------------------------------------------------------------------
module hps_min (
    output h2f_reset_reset ,
    output emac0_app_rst_reset_n ,
    input  hps_io_hps_osc_clk ,
    inout  hps_io_sdmmc_data0 ,
    inout  hps_io_sdmmc_data1 ,
    output hps_io_sdmmc_cclk ,
    inout  hps_io_sdmmc_data2 ,
    inout  hps_io_sdmmc_data3 ,
    inout  hps_io_sdmmc_cmd ,
    input  hps_io_usb0_clk ,
    output hps_io_usb0_stp ,
    input  hps_io_usb0_dir ,
    inout  hps_io_usb0_data0 ,
    inout  hps_io_usb0_data1 ,
    input  hps_io_usb0_nxt ,
    inout  hps_io_usb0_data2 ,
    inout  hps_io_usb0_data3 ,
    inout  hps_io_usb0_data4 ,
    inout  hps_io_usb0_data5 ,
    inout  hps_io_usb0_data6 ,
    inout  hps_io_usb0_data7 ,
    output hps_io_emac0_tx_clk ,
    output hps_io_emac0_tx_ctl ,
    input  hps_io_emac0_rx_clk ,
    input  hps_io_emac0_rx_ctl ,
    output hps_io_emac0_txd0 ,
    output hps_io_emac0_txd1 ,
    input  hps_io_emac0_rxd0 ,
    input  hps_io_emac0_rxd1 ,
    output hps_io_emac0_txd2 ,
    output hps_io_emac0_txd3 ,
    input  hps_io_emac0_rxd2 ,
    input  hps_io_emac0_rxd3 ,
    inout  hps_io_mdio0_mdio ,
    output hps_io_mdio0_mdc ,
    output hps_io_spim0_clk ,
    output hps_io_spim0_mosi ,
    output hps_io_spim0_ss0_n ,
    output hps_io_uart1_tx ,
    input  hps_io_uart1_rx ,
    inout  hps_io_i2c1_sda ,
    inout  hps_io_i2c1_scl ,
    inout  hps_io_gpio28 ,
    inout  hps_io_gpio32 ,
    inout  hps_io_gpio33 ,
    inout  hps_io_gpio34 ,
    inout  hps_io_gpio35 ,
    inout  hps_io_gpio40 ,
    inout  hps_io_gpio41 ,
    inout  hps_io_gpio42 ,
    output mem_0_cke ,
    output mem_0_odt ,
    output mem_0_cs_n ,
    output [16:0] mem_0_a ,
    output [1:0] mem_0_ba ,
    output mem_0_bg ,
    output mem_0_act_n ,
    output mem_0_par ,
    inout  [31:0] mem_0_dq ,
    inout  [3:0] mem_0_dqs_t ,
    inout  [3:0] mem_0_dqs_c ,
    input  mem_0_alert_n ,
    inout  [3:0] mem_0_dbi_n ,
    output mem_0_ck_t ,
    output mem_0_ck_c ,
    output mem_0_reset_n ,
    input  oct_rzqin_0 ,
    input  ref_clk
);

    // ---- internal HPS <-> EMIF NoC bus (io96b0_to_hps) ----
    wire [39:0] io96b_axi4_ch0_araddr;
    wire [1:0] io96b_axi4_ch0_arburst;
    wire [6:0] io96b_axi4_ch0_arid;
    wire [7:0] io96b_axi4_ch0_arlen;
    wire  io96b_axi4_ch0_arlock;
    wire [2:0] io96b_axi4_ch0_arprot;
    wire [3:0] io96b_axi4_ch0_arqos;
    wire  io96b_axi4_ch0_arready;
    wire [2:0] io96b_axi4_ch0_arsize;
    wire [13:0] io96b_axi4_ch0_aruser;
    wire  io96b_axi4_ch0_arvalid;
    wire [39:0] io96b_axi4_ch0_awaddr;
    wire [1:0] io96b_axi4_ch0_awburst;
    wire [6:0] io96b_axi4_ch0_awid;
    wire [7:0] io96b_axi4_ch0_awlen;
    wire  io96b_axi4_ch0_awlock;
    wire [2:0] io96b_axi4_ch0_awprot;
    wire [3:0] io96b_axi4_ch0_awqos;
    wire  io96b_axi4_ch0_awready;
    wire [2:0] io96b_axi4_ch0_awsize;
    wire [13:0] io96b_axi4_ch0_awuser;
    wire  io96b_axi4_ch0_awvalid;
    wire [6:0] io96b_axi4_ch0_bid;
    wire  io96b_axi4_ch0_bready;
    wire [1:0] io96b_axi4_ch0_bresp;
    wire  io96b_axi4_ch0_bvalid;
    wire  io96b_axi4_ch0_clk;
    wire [255:0] io96b_axi4_ch0_rdata;
    wire  io96b_axi4_ch0_reset_n;
    wire [6:0] io96b_axi4_ch0_rid;
    wire  io96b_axi4_ch0_rlast;
    wire  io96b_axi4_ch0_rready;
    wire [1:0] io96b_axi4_ch0_rresp;
    wire [31:0] io96b_axi4_ch0_ruser;
    wire  io96b_axi4_ch0_rvalid;
    wire [255:0] io96b_axi4_ch0_wdata;
    wire  io96b_axi4_ch0_wlast;
    wire  io96b_axi4_ch0_wready;
    wire [31:0] io96b_axi4_ch0_wstrb;
    wire [31:0] io96b_axi4_ch0_wuser;
    wire  io96b_axi4_ch0_wvalid;
    wire [26:0] io96b_ch0_axil_araddr;
    wire [2:0] io96b_ch0_axil_arprot;
    wire  io96b_ch0_axil_arready;
    wire  io96b_ch0_axil_arvalid;
    wire [26:0] io96b_ch0_axil_awaddr;
    wire [2:0] io96b_ch0_axil_awprot;
    wire  io96b_ch0_axil_awready;
    wire  io96b_ch0_axil_awvalid;
    wire  io96b_ch0_axil_bready;
    wire [1:0] io96b_ch0_axil_bresp;
    wire  io96b_ch0_axil_bvalid;
    wire  io96b_ch0_axil_clk;
    wire [31:0] io96b_ch0_axil_rdata;
    wire  io96b_ch0_axil_reset_n;
    wire  io96b_ch0_axil_rready;
    wire [1:0] io96b_ch0_axil_rresp;
    wire  io96b_ch0_axil_rvalid;
    wire [31:0] io96b_ch0_axil_wdata;
    wire  io96b_ch0_axil_wready;
    wire [3:0] io96b_ch0_axil_wstrb;
    wire  io96b_ch0_axil_wvalid;

    agilex_hps u_hps (
        .h2f_reset_reset (h2f_reset_reset) ,
        .emac0_app_rst_reset_n (emac0_app_rst_reset_n) ,
        .hps_io_hps_osc_clk (hps_io_hps_osc_clk) ,
        .hps_io_sdmmc_data0 (hps_io_sdmmc_data0) ,
        .hps_io_sdmmc_data1 (hps_io_sdmmc_data1) ,
        .hps_io_sdmmc_cclk (hps_io_sdmmc_cclk) ,
        .hps_io_sdmmc_data2 (hps_io_sdmmc_data2) ,
        .hps_io_sdmmc_data3 (hps_io_sdmmc_data3) ,
        .hps_io_sdmmc_cmd (hps_io_sdmmc_cmd) ,
        .hps_io_usb0_clk (hps_io_usb0_clk) ,
        .hps_io_usb0_stp (hps_io_usb0_stp) ,
        .hps_io_usb0_dir (hps_io_usb0_dir) ,
        .hps_io_usb0_data0 (hps_io_usb0_data0) ,
        .hps_io_usb0_data1 (hps_io_usb0_data1) ,
        .hps_io_usb0_nxt (hps_io_usb0_nxt) ,
        .hps_io_usb0_data2 (hps_io_usb0_data2) ,
        .hps_io_usb0_data3 (hps_io_usb0_data3) ,
        .hps_io_usb0_data4 (hps_io_usb0_data4) ,
        .hps_io_usb0_data5 (hps_io_usb0_data5) ,
        .hps_io_usb0_data6 (hps_io_usb0_data6) ,
        .hps_io_usb0_data7 (hps_io_usb0_data7) ,
        .hps_io_emac0_tx_clk (hps_io_emac0_tx_clk) ,
        .hps_io_emac0_tx_ctl (hps_io_emac0_tx_ctl) ,
        .hps_io_emac0_rx_clk (hps_io_emac0_rx_clk) ,
        .hps_io_emac0_rx_ctl (hps_io_emac0_rx_ctl) ,
        .hps_io_emac0_txd0 (hps_io_emac0_txd0) ,
        .hps_io_emac0_txd1 (hps_io_emac0_txd1) ,
        .hps_io_emac0_rxd0 (hps_io_emac0_rxd0) ,
        .hps_io_emac0_rxd1 (hps_io_emac0_rxd1) ,
        .hps_io_emac0_txd2 (hps_io_emac0_txd2) ,
        .hps_io_emac0_txd3 (hps_io_emac0_txd3) ,
        .hps_io_emac0_rxd2 (hps_io_emac0_rxd2) ,
        .hps_io_emac0_rxd3 (hps_io_emac0_rxd3) ,
        .hps_io_mdio0_mdio (hps_io_mdio0_mdio) ,
        .hps_io_mdio0_mdc (hps_io_mdio0_mdc) ,
        .hps_io_spim0_clk (hps_io_spim0_clk) ,
        .hps_io_spim0_mosi (hps_io_spim0_mosi) ,
        .hps_io_spim0_ss0_n (hps_io_spim0_ss0_n) ,
        .hps_io_uart1_tx (hps_io_uart1_tx) ,
        .hps_io_uart1_rx (hps_io_uart1_rx) ,
        .hps_io_i2c1_sda (hps_io_i2c1_sda) ,
        .hps_io_i2c1_scl (hps_io_i2c1_scl) ,
        .hps_io_gpio28 (hps_io_gpio28) ,
        .hps_io_gpio32 (hps_io_gpio32) ,
        .hps_io_gpio33 (hps_io_gpio33) ,
        .hps_io_gpio34 (hps_io_gpio34) ,
        .hps_io_gpio35 (hps_io_gpio35) ,
        .hps_io_gpio40 (hps_io_gpio40) ,
        .hps_io_gpio41 (hps_io_gpio41) ,
        .hps_io_gpio42 (hps_io_gpio42) ,
        .io96b0_to_hps_ch0_axil_clk (io96b_ch0_axil_clk) ,
        .io96b0_to_hps_ch0_axil_reset_n (io96b_ch0_axil_reset_n) ,
        .io96b0_to_hps_ch0_axil_arready (io96b_ch0_axil_arready) ,
        .io96b0_to_hps_ch0_axil_awready (io96b_ch0_axil_awready) ,
        .io96b0_to_hps_ch0_axil_bresp (io96b_ch0_axil_bresp) ,
        .io96b0_to_hps_ch0_axil_bvalid (io96b_ch0_axil_bvalid) ,
        .io96b0_to_hps_ch0_axil_rdata (io96b_ch0_axil_rdata) ,
        .io96b0_to_hps_ch0_axil_rresp (io96b_ch0_axil_rresp) ,
        .io96b0_to_hps_ch0_axil_rvalid (io96b_ch0_axil_rvalid) ,
        .io96b0_to_hps_ch0_axil_wready (io96b_ch0_axil_wready) ,
        .io96b0_to_hps_ch0_axil_araddr (io96b_ch0_axil_araddr) ,
        .io96b0_to_hps_ch0_axil_arvalid (io96b_ch0_axil_arvalid) ,
        .io96b0_to_hps_ch0_axil_awaddr (io96b_ch0_axil_awaddr) ,
        .io96b0_to_hps_ch0_axil_awvalid (io96b_ch0_axil_awvalid) ,
        .io96b0_to_hps_ch0_axil_bready (io96b_ch0_axil_bready) ,
        .io96b0_to_hps_ch0_axil_rready (io96b_ch0_axil_rready) ,
        .io96b0_to_hps_ch0_axil_wdata (io96b_ch0_axil_wdata) ,
        .io96b0_to_hps_ch0_axil_wstrb (io96b_ch0_axil_wstrb) ,
        .io96b0_to_hps_ch0_axil_wvalid (io96b_ch0_axil_wvalid) ,
        .io96b0_to_hps_ch0_axil_arprot (io96b_ch0_axil_arprot) ,
        .io96b0_to_hps_ch0_axil_awprot (io96b_ch0_axil_awprot) ,
        .io96b0_to_hps_axi4_ch0_clk (io96b_axi4_ch0_clk) ,
        .io96b0_to_hps_axi4_ch0_reset_n (io96b_axi4_ch0_reset_n) ,
        .io96b0_to_hps_axi4_ch0_arready (io96b_axi4_ch0_arready) ,
        .io96b0_to_hps_axi4_ch0_awready (io96b_axi4_ch0_awready) ,
        .io96b0_to_hps_axi4_ch0_bid (io96b_axi4_ch0_bid) ,
        .io96b0_to_hps_axi4_ch0_bresp (io96b_axi4_ch0_bresp) ,
        .io96b0_to_hps_axi4_ch0_bvalid (io96b_axi4_ch0_bvalid) ,
        .io96b0_to_hps_axi4_ch0_rdata (io96b_axi4_ch0_rdata) ,
        .io96b0_to_hps_axi4_ch0_rid (io96b_axi4_ch0_rid) ,
        .io96b0_to_hps_axi4_ch0_rlast (io96b_axi4_ch0_rlast) ,
        .io96b0_to_hps_axi4_ch0_rresp (io96b_axi4_ch0_rresp) ,
        .io96b0_to_hps_axi4_ch0_ruser (io96b_axi4_ch0_ruser) ,
        .io96b0_to_hps_axi4_ch0_rvalid (io96b_axi4_ch0_rvalid) ,
        .io96b0_to_hps_axi4_ch0_wready (io96b_axi4_ch0_wready) ,
        .io96b0_to_hps_axi4_ch0_araddr (io96b_axi4_ch0_araddr) ,
        .io96b0_to_hps_axi4_ch0_arburst (io96b_axi4_ch0_arburst) ,
        .io96b0_to_hps_axi4_ch0_arid (io96b_axi4_ch0_arid) ,
        .io96b0_to_hps_axi4_ch0_arlen (io96b_axi4_ch0_arlen) ,
        .io96b0_to_hps_axi4_ch0_arlock (io96b_axi4_ch0_arlock) ,
        .io96b0_to_hps_axi4_ch0_arqos (io96b_axi4_ch0_arqos) ,
        .io96b0_to_hps_axi4_ch0_arsize (io96b_axi4_ch0_arsize) ,
        .io96b0_to_hps_axi4_ch0_aruser (io96b_axi4_ch0_aruser) ,
        .io96b0_to_hps_axi4_ch0_arvalid (io96b_axi4_ch0_arvalid) ,
        .io96b0_to_hps_axi4_ch0_awaddr (io96b_axi4_ch0_awaddr) ,
        .io96b0_to_hps_axi4_ch0_awburst (io96b_axi4_ch0_awburst) ,
        .io96b0_to_hps_axi4_ch0_awid (io96b_axi4_ch0_awid) ,
        .io96b0_to_hps_axi4_ch0_awlen (io96b_axi4_ch0_awlen) ,
        .io96b0_to_hps_axi4_ch0_awlock (io96b_axi4_ch0_awlock) ,
        .io96b0_to_hps_axi4_ch0_awqos (io96b_axi4_ch0_awqos) ,
        .io96b0_to_hps_axi4_ch0_awsize (io96b_axi4_ch0_awsize) ,
        .io96b0_to_hps_axi4_ch0_awuser (io96b_axi4_ch0_awuser) ,
        .io96b0_to_hps_axi4_ch0_awvalid (io96b_axi4_ch0_awvalid) ,
        .io96b0_to_hps_axi4_ch0_bready (io96b_axi4_ch0_bready) ,
        .io96b0_to_hps_axi4_ch0_rready (io96b_axi4_ch0_rready) ,
        .io96b0_to_hps_axi4_ch0_wdata (io96b_axi4_ch0_wdata) ,
        .io96b0_to_hps_axi4_ch0_wlast (io96b_axi4_ch0_wlast) ,
        .io96b0_to_hps_axi4_ch0_wstrb (io96b_axi4_ch0_wstrb) ,
        .io96b0_to_hps_axi4_ch0_wuser (io96b_axi4_ch0_wuser) ,
        .io96b0_to_hps_axi4_ch0_wvalid (io96b_axi4_ch0_wvalid) ,
        .io96b0_to_hps_axi4_ch0_arprot (io96b_axi4_ch0_arprot) ,
        .io96b0_to_hps_axi4_ch0_awprot (io96b_axi4_ch0_awprot)
    );

    emif_io96b_hps u_emif (
        .noc_aclk_0 (io96b_axi4_ch0_clk) ,
        .noc_rst_n_0 (io96b_axi4_ch0_reset_n) ,
        .s0_noc_axi4lite_clock (io96b_ch0_axil_clk) ,
        .s0_noc_axi4lite_reset_n (io96b_ch0_axil_reset_n) ,
        .s0_noc_axi4lite_awaddr (io96b_ch0_axil_awaddr) ,
        .s0_noc_axi4lite_awvalid (io96b_ch0_axil_awvalid) ,
        .s0_noc_axi4lite_awready (io96b_ch0_axil_awready) ,
        .s0_noc_axi4lite_araddr (io96b_ch0_axil_araddr) ,
        .s0_noc_axi4lite_arvalid (io96b_ch0_axil_arvalid) ,
        .s0_noc_axi4lite_arready (io96b_ch0_axil_arready) ,
        .s0_noc_axi4lite_wdata (io96b_ch0_axil_wdata) ,
        .s0_noc_axi4lite_wvalid (io96b_ch0_axil_wvalid) ,
        .s0_noc_axi4lite_wready (io96b_ch0_axil_wready) ,
        .s0_noc_axi4lite_rresp (io96b_ch0_axil_rresp) ,
        .s0_noc_axi4lite_rdata (io96b_ch0_axil_rdata) ,
        .s0_noc_axi4lite_rvalid (io96b_ch0_axil_rvalid) ,
        .s0_noc_axi4lite_rready (io96b_ch0_axil_rready) ,
        .s0_noc_axi4lite_bresp (io96b_ch0_axil_bresp) ,
        .s0_noc_axi4lite_bvalid (io96b_ch0_axil_bvalid) ,
        .s0_noc_axi4lite_bready (io96b_ch0_axil_bready) ,
        .s0_noc_axi4lite_awprot (io96b_ch0_axil_awprot) ,
        .s0_noc_axi4lite_wstrb (io96b_ch0_axil_wstrb) ,
        .s0_noc_axi4lite_arprot (io96b_ch0_axil_arprot) ,
        .s0_axi4_awaddr (io96b_axi4_ch0_awaddr) ,
        .s0_axi4_awburst (io96b_axi4_ch0_awburst) ,
        .s0_axi4_awid (io96b_axi4_ch0_awid) ,
        .s0_axi4_awlen (io96b_axi4_ch0_awlen) ,
        .s0_axi4_awlock (io96b_axi4_ch0_awlock) ,
        .s0_axi4_awqos (io96b_axi4_ch0_awqos) ,
        .s0_axi4_awsize (io96b_axi4_ch0_awsize) ,
        .s0_axi4_awvalid (io96b_axi4_ch0_awvalid) ,
        .s0_axi4_awuser (io96b_axi4_ch0_awuser) ,
        .s0_axi4_awprot (io96b_axi4_ch0_awprot) ,
        .s0_axi4_awready (io96b_axi4_ch0_awready) ,
        .s0_axi4_araddr (io96b_axi4_ch0_araddr) ,
        .s0_axi4_arburst (io96b_axi4_ch0_arburst) ,
        .s0_axi4_arid (io96b_axi4_ch0_arid) ,
        .s0_axi4_arlen (io96b_axi4_ch0_arlen) ,
        .s0_axi4_arlock (io96b_axi4_ch0_arlock) ,
        .s0_axi4_arqos (io96b_axi4_ch0_arqos) ,
        .s0_axi4_arsize (io96b_axi4_ch0_arsize) ,
        .s0_axi4_arvalid (io96b_axi4_ch0_arvalid) ,
        .s0_axi4_aruser (io96b_axi4_ch0_aruser) ,
        .s0_axi4_arprot (io96b_axi4_ch0_arprot) ,
        .s0_axi4_arready (io96b_axi4_ch0_arready) ,
        .s0_axi4_wdata (io96b_axi4_ch0_wdata) ,
        .s0_axi4_wstrb (io96b_axi4_ch0_wstrb) ,
        .s0_axi4_wlast (io96b_axi4_ch0_wlast) ,
        .s0_axi4_wvalid (io96b_axi4_ch0_wvalid) ,
        .s0_axi4_wready (io96b_axi4_ch0_wready) ,
        .s0_axi4_bready (io96b_axi4_ch0_bready) ,
        .s0_axi4_bid (io96b_axi4_ch0_bid) ,
        .s0_axi4_bresp (io96b_axi4_ch0_bresp) ,
        .s0_axi4_bvalid (io96b_axi4_ch0_bvalid) ,
        .s0_axi4_rready (io96b_axi4_ch0_rready) ,
        .s0_axi4_rdata (io96b_axi4_ch0_rdata) ,
        .s0_axi4_rid (io96b_axi4_ch0_rid) ,
        .s0_axi4_rlast (io96b_axi4_ch0_rlast) ,
        .s0_axi4_rresp (io96b_axi4_ch0_rresp) ,
        .s0_axi4_rvalid (io96b_axi4_ch0_rvalid) ,
        .s0_axi4_wuser (io96b_axi4_ch0_wuser) ,
        .s0_axi4_ruser (io96b_axi4_ch0_ruser) ,
        .mem_0_cke (mem_0_cke) ,
        .mem_0_odt (mem_0_odt) ,
        .mem_0_cs_n (mem_0_cs_n) ,
        .mem_0_a (mem_0_a) ,
        .mem_0_ba (mem_0_ba) ,
        .mem_0_bg (mem_0_bg) ,
        .mem_0_act_n (mem_0_act_n) ,
        .mem_0_par (mem_0_par) ,
        .mem_0_dq (mem_0_dq) ,
        .mem_0_dqs_t (mem_0_dqs_t) ,
        .mem_0_dqs_c (mem_0_dqs_c) ,
        .mem_0_alert_n (mem_0_alert_n) ,
        .mem_0_dbi_n (mem_0_dbi_n) ,
        .mem_0_ck_t (mem_0_ck_t) ,
        .mem_0_ck_c (mem_0_ck_c) ,
        .mem_0_reset_n (mem_0_reset_n) ,
        .oct_rzqin_0 (oct_rzqin_0) ,
        .ref_clk (ref_clk)
    );

endmodule
