------------------------------------------------------------------------
-- de25_soc_top - DE25-Standard (Agilex 5) SoC bring-up.
--
--   * hps_subsystem : Agilex 5 HPS + HPS-EMIF DDR4, EMAC0 (RGMII+MDIO),
--                     SD/MMC, UART1 console, I2C1.  H2F / F2SDRAM / the
--                     F2H ACE5-Lite port are disabled; LWH2F (the
--                     lightweight HPS-to-FPGA bridge) and the F2H
--                     interrupts stay enabled but are not wired to
--                     anything in the fabric yet - same as the sibling
--                     de25_nano_testproject / datacenter_peak_shaving
--                     designs this is adapted from (see hps/README.md).
--   * de25_uart_top : the fabric UART + fpga_interconnect register block,
--                     unchanged, on GPIO_D[0]/[1].  Runs independently of
--                     the HPS - not reachable over lwhps2fpga (yet).
--
-- hps_subsystem is a Platform Designer system (hps/hps_subsystem.qsys +
-- its per-instance .ip files) instantiated directly as a VHDL component -
-- see hps/README.md.  Pin / IO-standard assignments for the HPS and DDR4
-- pins come from the DE25 GHRD (hps/hps_pins.tcl).
------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;

entity de25_soc_top is
    port (
        -- ---- fabric side ----
        CLOCK0_50     : in    std_logic;                     -- 50 MHz  (PIN_CH128)
        CPU_RESET_n   : in    std_logic;                     -- active low (PIN_BM78)
        SW            : in    std_logic_vector(9 downto 0);
        KEY           : in    std_logic_vector(3 downto 0);
        LEDR          : out   std_logic_vector(9 downto 0);
        uart_rxd      : in    std_logic;                     -- GPIO_D[0]  (PIN_BK31)
        uart_txd      : out   std_logic;                     -- GPIO_D[1]  (PIN_BE43)

        -- ---- HPS ----
        HPS_CLK_25       : in    std_logic;
        HPS_ENET_MDC     : out   std_logic;
        HPS_ENET_MDIO    : inout std_logic;
        HPS_ENET_RX_CLK  : in    std_logic;
        HPS_ENET_RX_CTL  : in    std_logic;
        HPS_ENET_RX_DATA : in    std_logic_vector(3 downto 0);
        HPS_ENET_TX_CLK  : out   std_logic;
        HPS_ENET_TX_CTL  : out   std_logic;
        HPS_ENET_TX_DATA : out   std_logic_vector(3 downto 0);
        HPS_I2C_SCL      : inout std_logic;
        HPS_I2C_SDA      : inout std_logic;
        HPS_SD_CLK       : out   std_logic;
        HPS_SD_CMD       : inout std_logic;
        HPS_SD_DATA      : inout std_logic_vector(3 downto 0);
        HPS_UART_RX      : in    std_logic;
        HPS_UART_TX      : out   std_logic;

        -- ---- HPS DDR4 (EMIF) ----
        DDR4_REFCLK_p : in    std_logic;
        DDR4_A        : out   std_logic_vector(16 downto 0);
        DDR4_BA       : out   std_logic_vector(1 downto 0);
        DDR4_BG       : out   std_logic_vector(0 downto 0);
        DDR4_CK       : out   std_logic;
        DDR4_CK_n     : out   std_logic;
        DDR4_CKE      : out   std_logic;
        DDR4_DQS      : inout std_logic_vector(3 downto 0);
        DDR4_DQS_n    : inout std_logic_vector(3 downto 0);
        DDR4_DQ       : inout std_logic_vector(31 downto 0);
        DDR4_DBI_n    : inout std_logic_vector(3 downto 0);
        DDR4_CS_n     : out   std_logic;
        DDR4_RESET_n  : out   std_logic;
        DDR4_ODT      : out   std_logic;
        DDR4_PAR      : out   std_logic;
        DDR4_ALERT_n  : in    std_logic;
        DDR4_ACT_n    : out   std_logic;
        DDR4_RZQ      : in    std_logic
    );
end entity de25_soc_top;

architecture rtl of de25_soc_top is

    component de25_uart_top is
        generic (
            g_clock_divider : natural := 434;
            g_por_cycles    : natural := 1_048_575
        );
        port (
            CLOCK0_50    : in  std_logic;
            CPU_RESET_n  : in  std_logic;
            SW           : in  std_logic_vector(9 downto 0);
            KEY          : in  std_logic_vector(3 downto 0);
            LEDR         : out std_logic_vector(9 downto 0);
            uart_rxd     : in  std_logic;
            uart_txd     : out std_logic
        );
    end component de25_uart_top;

    -- generated by qsys-generate from hps/hps_subsystem.qsys - see
    -- hps/hps_subsystem/hps_subsystem_inst.vhd for the source of this
    -- declaration (regenerate and diff if the .qsys ever changes).
    component hps_subsystem is
        port (
            emif_io96b_hps_0_mem_0_mem_cke           : out   std_logic_vector(0 downto 0);
            emif_io96b_hps_0_mem_0_mem_odt           : out   std_logic_vector(0 downto 0);
            emif_io96b_hps_0_mem_0_mem_cs_n          : out   std_logic_vector(0 downto 0);
            emif_io96b_hps_0_mem_0_mem_a             : out   std_logic_vector(16 downto 0);
            emif_io96b_hps_0_mem_0_mem_ba            : out   std_logic_vector(1 downto 0);
            emif_io96b_hps_0_mem_0_mem_bg            : out   std_logic_vector(0 downto 0);
            emif_io96b_hps_0_mem_0_mem_act_n         : out   std_logic;
            emif_io96b_hps_0_mem_0_mem_par           : out   std_logic;
            emif_io96b_hps_0_mem_0_mem_dq            : inout std_logic_vector(31 downto 0) := (others => 'X');
            emif_io96b_hps_0_mem_0_mem_dqs_t         : inout std_logic_vector(3 downto 0)  := (others => 'X');
            emif_io96b_hps_0_mem_0_mem_dqs_c         : inout std_logic_vector(3 downto 0)  := (others => 'X');
            emif_io96b_hps_0_mem_0_mem_alert_n       : in    std_logic                     := 'X';
            emif_io96b_hps_0_mem_0_mem_dbi_n         : inout std_logic_vector(3 downto 0)  := (others => 'X');
            emif_io96b_hps_0_mem_ck_0_mem_ck_t       : out   std_logic_vector(0 downto 0);
            emif_io96b_hps_0_mem_ck_0_mem_ck_c       : out   std_logic_vector(0 downto 0);
            emif_io96b_hps_0_mem_reset_n_mem_reset_n : out   std_logic;
            emif_io96b_hps_0_oct_0_oct_rzqin         : in    std_logic                     := 'X';
            emif_io96b_hps_0_ref_clk_clk             : in    std_logic                     := 'X';
            hps_reset                                : out   std_logic;
            lwhps2fpga_axi_clock_clk                 : in    std_logic                     := 'X';
            lwhps2fpga_axi_reset_reset                : in    std_logic                     := 'X';
            lwhps2fpga_awid                          : out   std_logic_vector(3 downto 0);
            lwhps2fpga_awaddr                        : out   std_logic_vector(28 downto 0);
            lwhps2fpga_awlen                         : out   std_logic_vector(7 downto 0);
            lwhps2fpga_awsize                        : out   std_logic_vector(2 downto 0);
            lwhps2fpga_awburst                       : out   std_logic_vector(1 downto 0);
            lwhps2fpga_awlock                        : out   std_logic;
            lwhps2fpga_awcache                       : out   std_logic_vector(3 downto 0);
            lwhps2fpga_awprot                        : out   std_logic_vector(2 downto 0);
            lwhps2fpga_awvalid                       : out   std_logic;
            lwhps2fpga_awready                       : in    std_logic                     := 'X';
            lwhps2fpga_wdata                         : out   std_logic_vector(31 downto 0);
            lwhps2fpga_wstrb                         : out   std_logic_vector(3 downto 0);
            lwhps2fpga_wlast                         : out   std_logic;
            lwhps2fpga_wvalid                        : out   std_logic;
            lwhps2fpga_wready                        : in    std_logic                     := 'X';
            lwhps2fpga_bid                           : in    std_logic_vector(3 downto 0)  := (others => 'X');
            lwhps2fpga_bresp                         : in    std_logic_vector(1 downto 0)  := (others => 'X');
            lwhps2fpga_bvalid                        : in    std_logic                     := 'X';
            lwhps2fpga_bready                        : out   std_logic;
            lwhps2fpga_arid                          : out   std_logic_vector(3 downto 0);
            lwhps2fpga_araddr                        : out   std_logic_vector(28 downto 0);
            lwhps2fpga_arlen                         : out   std_logic_vector(7 downto 0);
            lwhps2fpga_arsize                        : out   std_logic_vector(2 downto 0);
            lwhps2fpga_arburst                       : out   std_logic_vector(1 downto 0);
            lwhps2fpga_arlock                        : out   std_logic;
            lwhps2fpga_arcache                       : out   std_logic_vector(3 downto 0);
            lwhps2fpga_arprot                        : out   std_logic_vector(2 downto 0);
            lwhps2fpga_arvalid                       : out   std_logic;
            lwhps2fpga_arready                       : in    std_logic                     := 'X';
            lwhps2fpga_rid                           : in    std_logic_vector(3 downto 0)  := (others => 'X');
            lwhps2fpga_rdata                         : in    std_logic_vector(31 downto 0) := (others => 'X');
            lwhps2fpga_rresp                         : in    std_logic_vector(1 downto 0)  := (others => 'X');
            lwhps2fpga_rlast                         : in    std_logic                     := 'X';
            lwhps2fpga_rvalid                        : in    std_logic                     := 'X';
            lwhps2fpga_rready                        : out   std_logic;
            hps_io_hps_osc_clk                       : in    std_logic                     := 'X';
            hps_io_sdmmc_data0                       : inout std_logic                     := 'X';
            hps_io_sdmmc_data1                       : inout std_logic                     := 'X';
            hps_io_sdmmc_cclk                        : out   std_logic;
            hps_io_sdmmc_data2                       : inout std_logic                     := 'X';
            hps_io_sdmmc_data3                       : inout std_logic                     := 'X';
            hps_io_sdmmc_cmd                         : inout std_logic                     := 'X';
            hps_io_emac0_tx_clk                      : out   std_logic;
            hps_io_emac0_tx_ctl                      : out   std_logic;
            hps_io_emac0_rx_clk                      : in    std_logic                     := 'X';
            hps_io_emac0_rx_ctl                      : in    std_logic                     := 'X';
            hps_io_emac0_txd0                        : out   std_logic;
            hps_io_emac0_txd1                        : out   std_logic;
            hps_io_emac0_rxd0                        : in    std_logic                     := 'X';
            hps_io_emac0_rxd1                        : in    std_logic                     := 'X';
            hps_io_emac0_txd2                        : out   std_logic;
            hps_io_emac0_txd3                        : out   std_logic;
            hps_io_emac0_rxd2                        : in    std_logic                     := 'X';
            hps_io_emac0_rxd3                        : in    std_logic                     := 'X';
            hps_io_mdio0_mdio                        : inout std_logic                     := 'X';
            hps_io_mdio0_mdc                         : out   std_logic;
            hps_io_uart1_tx                          : out   std_logic;
            hps_io_uart1_rx                          : in    std_logic                     := 'X';
            hps_io_i2c1_sda                          : inout std_logic                     := 'X';
            hps_io_i2c1_scl                          : inout std_logic                     := 'X';
            fpga2hps_interrupt_irq1_irq              : in    std_logic_vector(31 downto 0) := (others => 'X');
            fpga2hps_interrupt_irq0_irq              : in    std_logic_vector(31 downto 0) := (others => 'X');
            ninit_done_ninit_done                    : out   std_logic
        );
    end component hps_subsystem;

    signal ninit_done : std_logic;

begin

    ------------------------------------------------------------------
    -- fabric UART + register block (see de25_uart_top.vhd) - stands alone
    ------------------------------------------------------------------
    u_fabric : component de25_uart_top
        port map (
            CLOCK0_50   => CLOCK0_50,
            CPU_RESET_n => CPU_RESET_n,
            SW          => SW,
            KEY         => KEY,
            LEDR        => LEDR,
            uart_rxd    => uart_rxd,
            uart_txd    => uart_txd
        );

    ------------------------------------------------------------------
    -- HPS + HPS-EMIF DDR4 (see hps/hps_subsystem.qsys, GENERATED)
    ------------------------------------------------------------------
    u_hps : component hps_subsystem
        port map (
            emif_io96b_hps_0_mem_0_mem_cke(0)        => DDR4_CKE,
            emif_io96b_hps_0_mem_0_mem_odt(0)         => DDR4_ODT,
            emif_io96b_hps_0_mem_0_mem_cs_n(0)        => DDR4_CS_n,
            emif_io96b_hps_0_mem_0_mem_a              => DDR4_A,
            emif_io96b_hps_0_mem_0_mem_ba             => DDR4_BA,
            emif_io96b_hps_0_mem_0_mem_bg             => DDR4_BG,
            emif_io96b_hps_0_mem_0_mem_act_n          => DDR4_ACT_n,
            emif_io96b_hps_0_mem_0_mem_par            => DDR4_PAR,
            emif_io96b_hps_0_mem_0_mem_dq             => DDR4_DQ,
            emif_io96b_hps_0_mem_0_mem_dqs_t          => DDR4_DQS,
            emif_io96b_hps_0_mem_0_mem_dqs_c          => DDR4_DQS_n,
            emif_io96b_hps_0_mem_0_mem_alert_n        => DDR4_ALERT_n,
            emif_io96b_hps_0_mem_0_mem_dbi_n          => DDR4_DBI_n,
            emif_io96b_hps_0_mem_ck_0_mem_ck_t(0)     => DDR4_CK,
            emif_io96b_hps_0_mem_ck_0_mem_ck_c(0)     => DDR4_CK_n,
            emif_io96b_hps_0_mem_reset_n_mem_reset_n  => DDR4_RESET_n,
            emif_io96b_hps_0_oct_0_oct_rzqin          => DDR4_RZQ,
            emif_io96b_hps_0_ref_clk_clk              => DDR4_REFCLK_p,

            hps_reset                                 => open,

            -- lwhps2fpga: enabled (like the sibling projects) but not
            -- wired to anything in this fabric yet - tie the manager
            -- inputs to idle so it never stalls.
            lwhps2fpga_axi_clock_clk                  => CLOCK0_50,
            lwhps2fpga_axi_reset_reset                => not CPU_RESET_n,
            lwhps2fpga_awready                        => '0',
            lwhps2fpga_wready                         => '0',
            lwhps2fpga_bid                             => (others => '0'),
            lwhps2fpga_bresp                          => (others => '0'),
            lwhps2fpga_bvalid                         => '0',
            lwhps2fpga_arready                        => '0',
            lwhps2fpga_rid                             => (others => '0'),
            lwhps2fpga_rdata                          => (others => '0'),
            lwhps2fpga_rresp                          => (others => '0'),
            lwhps2fpga_rlast                          => '0',
            lwhps2fpga_rvalid                         => '0',
            lwhps2fpga_awid                            => open,
            lwhps2fpga_awaddr                         => open,
            lwhps2fpga_awlen                          => open,
            lwhps2fpga_awsize                         => open,
            lwhps2fpga_awburst                        => open,
            lwhps2fpga_awlock                         => open,
            lwhps2fpga_awcache                        => open,
            lwhps2fpga_awprot                         => open,
            lwhps2fpga_awvalid                        => open,
            lwhps2fpga_wdata                          => open,
            lwhps2fpga_wstrb                          => open,
            lwhps2fpga_wlast                          => open,
            lwhps2fpga_wvalid                         => open,
            lwhps2fpga_bready                         => open,
            lwhps2fpga_arid                            => open,
            lwhps2fpga_araddr                         => open,
            lwhps2fpga_arlen                          => open,
            lwhps2fpga_arsize                         => open,
            lwhps2fpga_arburst                        => open,
            lwhps2fpga_arlock                         => open,
            lwhps2fpga_arcache                        => open,
            lwhps2fpga_arprot                         => open,
            lwhps2fpga_arvalid                        => open,
            lwhps2fpga_rready                         => open,

            hps_io_hps_osc_clk                        => HPS_CLK_25,
            hps_io_sdmmc_data0                        => HPS_SD_DATA(0),
            hps_io_sdmmc_data1                        => HPS_SD_DATA(1),
            hps_io_sdmmc_cclk                         => HPS_SD_CLK,
            hps_io_sdmmc_data2                        => HPS_SD_DATA(2),
            hps_io_sdmmc_data3                        => HPS_SD_DATA(3),
            hps_io_sdmmc_cmd                          => HPS_SD_CMD,
            hps_io_emac0_tx_clk                       => HPS_ENET_TX_CLK,
            hps_io_emac0_tx_ctl                       => HPS_ENET_TX_CTL,
            hps_io_emac0_rx_clk                       => HPS_ENET_RX_CLK,
            hps_io_emac0_rx_ctl                       => HPS_ENET_RX_CTL,
            hps_io_emac0_txd0                         => HPS_ENET_TX_DATA(0),
            hps_io_emac0_txd1                         => HPS_ENET_TX_DATA(1),
            hps_io_emac0_rxd0                         => HPS_ENET_RX_DATA(0),
            hps_io_emac0_rxd1                         => HPS_ENET_RX_DATA(1),
            hps_io_emac0_txd2                         => HPS_ENET_TX_DATA(2),
            hps_io_emac0_txd3                         => HPS_ENET_TX_DATA(3),
            hps_io_emac0_rxd2                         => HPS_ENET_RX_DATA(2),
            hps_io_emac0_rxd3                         => HPS_ENET_RX_DATA(3),
            hps_io_mdio0_mdio                         => HPS_ENET_MDIO,
            hps_io_mdio0_mdc                          => HPS_ENET_MDC,
            hps_io_uart1_tx                           => HPS_UART_TX,
            hps_io_uart1_rx                           => HPS_UART_RX,
            hps_io_i2c1_sda                           => HPS_I2C_SDA,
            hps_io_i2c1_scl                           => HPS_I2C_SCL,

            -- F2H interrupts: left enabled (sibling-style) but unused
            fpga2hps_interrupt_irq0_irq                => (others => '0'),
            fpga2hps_interrupt_irq1_irq                => (others => '0'),

            ninit_done_ninit_done                     => ninit_done
        );

end architecture rtl;
