#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# program.sh - load a .sof onto the Terasic DE25-Standard (Agilex 5) over
#              JTAG, from WSL2, through the board's on-board Intel FPGA
#              Download Cable II (USB-Blaster II) that usbipd-win has
#              forwarded into this WSL distro.
#
#   usbipd (run on Windows, admin PowerShell) - do this first, every replug:
#       usbipd list
#       usbipd bind   --busid <b-p>          # once
#       usbipd attach --wsl --busid <b-p>
#
#   then, in WSL:
#       ./program.sh                         # program output_files/de25_uart.sof
#       ./program.sh path/to/other.sof       # program a specific file
#       ./program.sh --check                 # set up + jtagconfig, don't program
#       sudo ./program.sh --install-udev     # persistent 0666 rule (once)
#
# Env overrides:  QUARTUS_BIN=...  CABLE=<index>  DEVICE=<jtag index, default 1>
#
# NOTE: the UART for test_uart.py is NOT this cable.  It is the external
# 3.3 V USB-serial adapter wired to GPIO_D[0]/GPIO_D[1] (see README), which
# enumerates as its own /dev/ttyUSB* .
# ---------------------------------------------------------------------------
set -uo pipefail

QUARTUS_BIN="${QUARTUS_BIN:-$HOME/altera_pro/26.1.1/quartus/bin}"
CABLE="${CABLE:-1}"
DEVICE="${DEVICE:-1}"
UDEV_RULE=/etc/udev/rules.d/51-usbblaster.rules

SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"

die()  { echo "ERROR: $*" >&2; exit 1; }
note() { echo ">> $*"; }

# --- find the on-board USB-Blaster II in lsusb -----------------------------
# Intel/Altera USB-Blaster / USB-Blaster II : 09fb:6010 / 09fb:6810 / 09fb:6022
find_blaster() { lsusb | grep -iE 'ID 09fb:' | head -n1; }

LINE="$(find_blaster)"
if [ -z "$LINE" ]; then
    echo "No USB-Blaster visible in lsusb." >&2
    echo "On Windows (admin PowerShell):" >&2
    echo "    usbipd list" >&2
    echo "    usbipd attach --wsl --busid <b-p>" >&2
    exit 1
fi

VIDPID=$(sed -nE 's/.*ID ([0-9a-fA-F]{4}:[0-9a-fA-F]{4}).*/\1/p' <<<"$LINE")
VID=${VIDPID%:*}; PID=${VIDPID#*:}
BUS=$(awk '{print $2}' <<<"$LINE")
DEV=$(awk '{sub(/:/,"",$4); print $4}' <<<"$LINE")
note "blaster: $VIDPID  (bus $BUS dev $DEV)  [$LINE]"

if [ "${1:-}" = "--install-udev" ]; then
    [ -n "$SUDO" ] && die "run as root: sudo $0 --install-udev"
    cat > "$UDEV_RULE" <<EOF
# Terasic DE25-Standard on-board USB-Blaster II (auto-generated by program.sh)
SUBSYSTEM=="usb", ATTR{idVendor}=="09fb", MODE="0666"
EOF
    udevadm control --reload-rules
    udevadm trigger
    echo "wrote $UDEV_RULE - replug the board (usbipd attach again) to apply."
    exit 0
fi

# --- permissions on the raw USB node -------------------------------------
$SUDO chmod 666 "/dev/bus/usb/$BUS/$DEV" 2>/dev/null || true

# --- (re)start jtagd ---------------------------------------------------
pkill -x jtagd 2>/dev/null || true
sleep 1
"$QUARTUS_BIN/jtagd" 2>/dev/null || true
sleep 1

note "jtagconfig:"
"$QUARTUS_BIN/jtagconfig" || true

[ "${1:-}" = "--check" ] && exit 0

SOF="${1:-output_files/de25_uart.sof}"
[ -f "$SOF" ] || die "sof not found: $SOF  (build it first)"

note "programming $SOF  (cable index $CABLE, jtag device @$DEVICE)"
exec "$QUARTUS_BIN/quartus_pgm" -c "$CABLE" -m jtag -o "p;${SOF}@${DEVICE}"
